# Generated by Django 2.2 on 2020-04-24 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2020, 4, 24, 15, 58, 6, 487779, tzinfo=utc))),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
